### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by aaron4444** [xpdAcq/xpdtools#26]
when trying to install with conda forge, it says:
that the package is not available, even though conda-forge is my first channel. 

Building from source was fine. 

![conda](https://user-images.githubusercontent.com/20306451/37317524-b6379a54-263b-11e8-8edf-2cf8d59240b4.PNG)

**Comment by CJ-Wright** [comment]
Sorry! Thank you for reporting 
The issue is pyFAI doesn't currently have a conda recipe which builds on windows.

**Comment by CJ-Wright** [comment]
pyFAI now has a windows build so I'm going to close this. Please feel free to reopen if this is still an issue.
